/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"

#import "EDAMTypes.h"
#import "EDAMErrors.h"

enum EDAMSponsoredGroupRole {
  SponsoredGroupRole_GROUP_MEMBER = 1,
  SponsoredGroupRole_GROUP_ADMIN = 2,
  SponsoredGroupRole_GROUP_OWNER = 3
};

@interface EDAMPublicUserInfo : NSObject <NSCoding> {
  EDAMUserID __userId;
  NSString * __shardId;
  int __privilege;
  NSString * __username;
  NSString * __noteStoreUrl;

  BOOL __userId_isset;
  BOOL __shardId_isset;
  BOOL __privilege_isset;
  BOOL __username_isset;
  BOOL __noteStoreUrl_isset;
}

- (id) initWithUserId: (EDAMUserID) userId shardId: (NSString *) shardId privilege: (int) privilege username: (NSString *) username noteStoreUrl: (NSString *) noteStoreUrl;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=userId, setter=setUserId:) EDAMUserID userId;
@property (nonatomic, retain, getter=shardId, setter=setShardId:) NSString * shardId;
@property (nonatomic, getter=privilege, setter=setPrivilege:) int privilege;
@property (nonatomic, retain, getter=username, setter=setUsername:) NSString * username;
@property (nonatomic, retain, getter=noteStoreUrl, setter=setNoteStoreUrl:) NSString * noteStoreUrl;
#else

- (EDAMUserID) userId;
- (void) setUserId: (EDAMUserID) userId;

- (NSString *) shardId;
- (void) setShardId: (NSString *) shardId;

- (int) privilege;
- (void) setPrivilege: (int) privilege;

- (NSString *) username;
- (void) setUsername: (NSString *) username;

- (NSString *) noteStoreUrl;
- (void) setNoteStoreUrl: (NSString *) noteStoreUrl;

#endif

- (BOOL) userIdIsSet;
- (BOOL) shardIdIsSet;
- (BOOL) privilegeIsSet;
- (BOOL) usernameIsSet;
- (BOOL) noteStoreUrlIsSet;
@end

@interface EDAMPremiumInfo : NSObject <NSCoding> {
  EDAMTimestamp __currentTime;
  BOOL __premium;
  BOOL __premiumRecurring;
  EDAMTimestamp __premiumExpirationDate;
  BOOL __premiumExtendable;
  BOOL __premiumPending;
  BOOL __premiumCancellationPending;
  BOOL __canPurchaseUploadAllowance;
  NSString * __sponsoredGroupName;
  int __sponsoredGroupRole;

  BOOL __currentTime_isset;
  BOOL __premium_isset;
  BOOL __premiumRecurring_isset;
  BOOL __premiumExpirationDate_isset;
  BOOL __premiumExtendable_isset;
  BOOL __premiumPending_isset;
  BOOL __premiumCancellationPending_isset;
  BOOL __canPurchaseUploadAllowance_isset;
  BOOL __sponsoredGroupName_isset;
  BOOL __sponsoredGroupRole_isset;
}

- (id) initWithCurrentTime: (EDAMTimestamp) currentTime premium: (BOOL) premium premiumRecurring: (BOOL) premiumRecurring premiumExpirationDate: (EDAMTimestamp) premiumExpirationDate premiumExtendable: (BOOL) premiumExtendable premiumPending: (BOOL) premiumPending premiumCancellationPending: (BOOL) premiumCancellationPending canPurchaseUploadAllowance: (BOOL) canPurchaseUploadAllowance sponsoredGroupName: (NSString *) sponsoredGroupName sponsoredGroupRole: (int) sponsoredGroupRole;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=currentTime, setter=setCurrentTime:) EDAMTimestamp currentTime;
@property (nonatomic, getter=premium, setter=setPremium:) BOOL premium;
@property (nonatomic, getter=premiumRecurring, setter=setPremiumRecurring:) BOOL premiumRecurring;
@property (nonatomic, getter=premiumExpirationDate, setter=setPremiumExpirationDate:) EDAMTimestamp premiumExpirationDate;
@property (nonatomic, getter=premiumExtendable, setter=setPremiumExtendable:) BOOL premiumExtendable;
@property (nonatomic, getter=premiumPending, setter=setPremiumPending:) BOOL premiumPending;
@property (nonatomic, getter=premiumCancellationPending, setter=setPremiumCancellationPending:) BOOL premiumCancellationPending;
@property (nonatomic, getter=canPurchaseUploadAllowance, setter=setCanPurchaseUploadAllowance:) BOOL canPurchaseUploadAllowance;
@property (nonatomic, retain, getter=sponsoredGroupName, setter=setSponsoredGroupName:) NSString * sponsoredGroupName;
@property (nonatomic, getter=sponsoredGroupRole, setter=setSponsoredGroupRole:) int sponsoredGroupRole;
#else

- (EDAMTimestamp) currentTime;
- (void) setCurrentTime: (EDAMTimestamp) currentTime;

- (BOOL) premium;
- (void) setPremium: (BOOL) premium;

- (BOOL) premiumRecurring;
- (void) setPremiumRecurring: (BOOL) premiumRecurring;

- (EDAMTimestamp) premiumExpirationDate;
- (void) setPremiumExpirationDate: (EDAMTimestamp) premiumExpirationDate;

- (BOOL) premiumExtendable;
- (void) setPremiumExtendable: (BOOL) premiumExtendable;

- (BOOL) premiumPending;
- (void) setPremiumPending: (BOOL) premiumPending;

- (BOOL) premiumCancellationPending;
- (void) setPremiumCancellationPending: (BOOL) premiumCancellationPending;

- (BOOL) canPurchaseUploadAllowance;
- (void) setCanPurchaseUploadAllowance: (BOOL) canPurchaseUploadAllowance;

- (NSString *) sponsoredGroupName;
- (void) setSponsoredGroupName: (NSString *) sponsoredGroupName;

- (int) sponsoredGroupRole;
- (void) setSponsoredGroupRole: (int) sponsoredGroupRole;

#endif

- (BOOL) currentTimeIsSet;
- (BOOL) premiumIsSet;
- (BOOL) premiumRecurringIsSet;
- (BOOL) premiumExpirationDateIsSet;
- (BOOL) premiumExtendableIsSet;
- (BOOL) premiumPendingIsSet;
- (BOOL) premiumCancellationPendingIsSet;
- (BOOL) canPurchaseUploadAllowanceIsSet;
- (BOOL) sponsoredGroupNameIsSet;
- (BOOL) sponsoredGroupRoleIsSet;
@end

@interface EDAMAuthenticationResult : NSObject <NSCoding> {
  EDAMTimestamp __currentTime;
  NSString * __authenticationToken;
  EDAMTimestamp __expiration;
  EDAMUser * __user;
  EDAMPublicUserInfo * __publicUserInfo;
  NSString * __noteStoreUrl;
  NSString * __webApiUrlPrefix;

  BOOL __currentTime_isset;
  BOOL __authenticationToken_isset;
  BOOL __expiration_isset;
  BOOL __user_isset;
  BOOL __publicUserInfo_isset;
  BOOL __noteStoreUrl_isset;
  BOOL __webApiUrlPrefix_isset;
}

- (id) initWithCurrentTime: (EDAMTimestamp) currentTime authenticationToken: (NSString *) authenticationToken expiration: (EDAMTimestamp) expiration user: (EDAMUser *) user publicUserInfo: (EDAMPublicUserInfo *) publicUserInfo noteStoreUrl: (NSString *) noteStoreUrl webApiUrlPrefix: (NSString *) webApiUrlPrefix;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=currentTime, setter=setCurrentTime:) EDAMTimestamp currentTime;
@property (nonatomic, retain, getter=authenticationToken, setter=setAuthenticationToken:) NSString * authenticationToken;
@property (nonatomic, getter=expiration, setter=setExpiration:) EDAMTimestamp expiration;
@property (nonatomic, retain, getter=user, setter=setUser:) EDAMUser * user;
@property (nonatomic, retain, getter=publicUserInfo, setter=setPublicUserInfo:) EDAMPublicUserInfo * publicUserInfo;
@property (nonatomic, retain, getter=noteStoreUrl, setter=setNoteStoreUrl:) NSString * noteStoreUrl;
@property (nonatomic, retain, getter=webApiUrlPrefix, setter=setWebApiUrlPrefix:) NSString * webApiUrlPrefix;
#else

- (EDAMTimestamp) currentTime;
- (void) setCurrentTime: (EDAMTimestamp) currentTime;

- (NSString *) authenticationToken;
- (void) setAuthenticationToken: (NSString *) authenticationToken;

- (EDAMTimestamp) expiration;
- (void) setExpiration: (EDAMTimestamp) expiration;

- (EDAMUser *) user;
- (void) setUser: (EDAMUser *) user;

- (EDAMPublicUserInfo *) publicUserInfo;
- (void) setPublicUserInfo: (EDAMPublicUserInfo *) publicUserInfo;

- (NSString *) noteStoreUrl;
- (void) setNoteStoreUrl: (NSString *) noteStoreUrl;

- (NSString *) webApiUrlPrefix;
- (void) setWebApiUrlPrefix: (NSString *) webApiUrlPrefix;

#endif

- (BOOL) currentTimeIsSet;
- (BOOL) authenticationTokenIsSet;
- (BOOL) expirationIsSet;
- (BOOL) userIsSet;
- (BOOL) publicUserInfoIsSet;
- (BOOL) noteStoreUrlIsSet;
- (BOOL) webApiUrlPrefixIsSet;
@end

@interface EDAMBootstrapSettings : NSObject <NSCoding> {
  NSString * __serviceHost;
  NSString * __marketingUrl;
  NSString * __supportUrl;
  NSString * __accountEmailDomain;
  BOOL __enableFacebookSharing;
  BOOL __enableGiftSubscriptions;
  BOOL __enableSupportTickets;
  BOOL __enableSharedNotebooks;
  BOOL __enableSingleNoteSharing;
  BOOL __enableSponsoredAccounts;
  BOOL __enableTwitterSharing;

  BOOL __serviceHost_isset;
  BOOL __marketingUrl_isset;
  BOOL __supportUrl_isset;
  BOOL __accountEmailDomain_isset;
  BOOL __enableFacebookSharing_isset;
  BOOL __enableGiftSubscriptions_isset;
  BOOL __enableSupportTickets_isset;
  BOOL __enableSharedNotebooks_isset;
  BOOL __enableSingleNoteSharing_isset;
  BOOL __enableSponsoredAccounts_isset;
  BOOL __enableTwitterSharing_isset;
}

- (id) initWithServiceHost: (NSString *) serviceHost marketingUrl: (NSString *) marketingUrl supportUrl: (NSString *) supportUrl accountEmailDomain: (NSString *) accountEmailDomain enableFacebookSharing: (BOOL) enableFacebookSharing enableGiftSubscriptions: (BOOL) enableGiftSubscriptions enableSupportTickets: (BOOL) enableSupportTickets enableSharedNotebooks: (BOOL) enableSharedNotebooks enableSingleNoteSharing: (BOOL) enableSingleNoteSharing enableSponsoredAccounts: (BOOL) enableSponsoredAccounts enableTwitterSharing: (BOOL) enableTwitterSharing;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=serviceHost, setter=setServiceHost:) NSString * serviceHost;
@property (nonatomic, retain, getter=marketingUrl, setter=setMarketingUrl:) NSString * marketingUrl;
@property (nonatomic, retain, getter=supportUrl, setter=setSupportUrl:) NSString * supportUrl;
@property (nonatomic, retain, getter=accountEmailDomain, setter=setAccountEmailDomain:) NSString * accountEmailDomain;
@property (nonatomic, getter=enableFacebookSharing, setter=setEnableFacebookSharing:) BOOL enableFacebookSharing;
@property (nonatomic, getter=enableGiftSubscriptions, setter=setEnableGiftSubscriptions:) BOOL enableGiftSubscriptions;
@property (nonatomic, getter=enableSupportTickets, setter=setEnableSupportTickets:) BOOL enableSupportTickets;
@property (nonatomic, getter=enableSharedNotebooks, setter=setEnableSharedNotebooks:) BOOL enableSharedNotebooks;
@property (nonatomic, getter=enableSingleNoteSharing, setter=setEnableSingleNoteSharing:) BOOL enableSingleNoteSharing;
@property (nonatomic, getter=enableSponsoredAccounts, setter=setEnableSponsoredAccounts:) BOOL enableSponsoredAccounts;
@property (nonatomic, getter=enableTwitterSharing, setter=setEnableTwitterSharing:) BOOL enableTwitterSharing;
#else

- (NSString *) serviceHost;
- (void) setServiceHost: (NSString *) serviceHost;

- (NSString *) marketingUrl;
- (void) setMarketingUrl: (NSString *) marketingUrl;

- (NSString *) supportUrl;
- (void) setSupportUrl: (NSString *) supportUrl;

- (NSString *) accountEmailDomain;
- (void) setAccountEmailDomain: (NSString *) accountEmailDomain;

- (BOOL) enableFacebookSharing;
- (void) setEnableFacebookSharing: (BOOL) enableFacebookSharing;

- (BOOL) enableGiftSubscriptions;
- (void) setEnableGiftSubscriptions: (BOOL) enableGiftSubscriptions;

- (BOOL) enableSupportTickets;
- (void) setEnableSupportTickets: (BOOL) enableSupportTickets;

- (BOOL) enableSharedNotebooks;
- (void) setEnableSharedNotebooks: (BOOL) enableSharedNotebooks;

- (BOOL) enableSingleNoteSharing;
- (void) setEnableSingleNoteSharing: (BOOL) enableSingleNoteSharing;

- (BOOL) enableSponsoredAccounts;
- (void) setEnableSponsoredAccounts: (BOOL) enableSponsoredAccounts;

- (BOOL) enableTwitterSharing;
- (void) setEnableTwitterSharing: (BOOL) enableTwitterSharing;

#endif

- (BOOL) serviceHostIsSet;
- (BOOL) marketingUrlIsSet;
- (BOOL) supportUrlIsSet;
- (BOOL) accountEmailDomainIsSet;
- (BOOL) enableFacebookSharingIsSet;
- (BOOL) enableGiftSubscriptionsIsSet;
- (BOOL) enableSupportTicketsIsSet;
- (BOOL) enableSharedNotebooksIsSet;
- (BOOL) enableSingleNoteSharingIsSet;
- (BOOL) enableSponsoredAccountsIsSet;
- (BOOL) enableTwitterSharingIsSet;
@end

@interface EDAMBootstrapProfile : NSObject <NSCoding> {
  NSString * __name;
  EDAMBootstrapSettings * __settings;

  BOOL __name_isset;
  BOOL __settings_isset;
}

- (id) initWithName: (NSString *) name settings: (EDAMBootstrapSettings *) settings;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, retain, getter=settings, setter=setSettings:) EDAMBootstrapSettings * settings;
#else

- (NSString *) name;
- (void) setName: (NSString *) name;

- (EDAMBootstrapSettings *) settings;
- (void) setSettings: (EDAMBootstrapSettings *) settings;

#endif

- (BOOL) nameIsSet;
- (BOOL) settingsIsSet;
@end

@interface EDAMBootstrapInfo : NSObject <NSCoding> {
  NSArray * __profiles;

  BOOL __profiles_isset;
}

- (id) initWithProfiles: (NSArray *) profiles;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=profiles, setter=setProfiles:) NSArray * profiles;
#else

- (NSArray *) profiles;
- (void) setProfiles: (NSArray *) profiles;

#endif

- (BOOL) profilesIsSet;
@end

@protocol EDAMUserStore <NSObject>
- (BOOL) checkVersion: (NSString *) clientName : (int16_t) edamVersionMajor : (int16_t) edamVersionMinor;  // throws TException
- (EDAMBootstrapInfo *) getBootstrapInfo: (NSString *) locale;  // throws TException
- (EDAMAuthenticationResult *) authenticate: (NSString *) username : (NSString *) password : (NSString *) consumerKey : (NSString *) consumerSecret;  // throws EDAMUserException *, EDAMSystemException *, TException
- (EDAMAuthenticationResult *) refreshAuthentication: (NSString *) authenticationToken;  // throws EDAMUserException *, EDAMSystemException *, TException
- (EDAMUser *) getUser: (NSString *) authenticationToken;  // throws EDAMUserException *, EDAMSystemException *, TException
- (EDAMPublicUserInfo *) getPublicUserInfo: (NSString *) username;  // throws EDAMNotFoundException *, EDAMSystemException *, EDAMUserException *, TException
- (EDAMPremiumInfo *) getPremiumInfo: (NSString *) authenticationToken;  // throws EDAMUserException *, EDAMSystemException *, TException
- (NSString *) getNoteStoreUrl: (NSString *) authenticationToken;  // throws EDAMUserException *, EDAMSystemException *, TException
@end

@interface EDAMUserStoreClient : NSObject <EDAMUserStore> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface EDAMUserStoreProcessor : NSObject <TProcessor> {
  id <EDAMUserStore> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithUserStore: (id <EDAMUserStore>) service;
- (id<EDAMUserStore>) service;
@end

@interface EDAMUserStoreConstants : NSObject {
}
+ (int16_t) EDAM_VERSION_MAJOR;
+ (int16_t) EDAM_VERSION_MINOR;
@end
