
language: objective-c

before_install:
    - export LANG=en_US.UTF-8
    - env
    - locale
    - gem install cocoapods --pre --quiet
    - pod --version
    - pod setup --silent

script:
    - pod lib lint --subspec=ShareKit/Core
    - pod lib lint --subspec=ShareKit/NoARC
    - pod lib lint --subspec=ShareKit/Reachability
    - pod lib lint --subspec=ShareKit/Evernote
    - pod lib lint --subspec=ShareKit/Facebook
    - pod lib lint --subspec=ShareKit/Flickr
    - pod lib lint --subspec=ShareKit/Foursquare
    - pod lib lint --subspec=ShareKit/Delicious
    - pod lib lint --subspec=ShareKit/Hatena
    - pod lib lint --subspec=ShareKit/Kippt
    - pod lib lint --subspec=ShareKit/Plurk
    - pod lib lint --subspec=ShareKit/Pocket
    - pod lib lint --subspec=ShareKit/Diigo
    - pod lib lint --subspec=ShareKit/Dropbox
    - pod lib lint --subspec=ShareKit/Instapaper
    - pod lib lint --subspec=ShareKit/LinkedIn
    - pod lib lint --subspec=ShareKit/Pinboard
    - pod lib lint --subspec=ShareKit/Readability
    - pod lib lint --subspec=ShareKit/ReadItLater
    - pod lib lint --subspec=ShareKit/Tumblr
    - pod lib lint --subspec=ShareKit/Twitter
    - pod lib lint --subspec=ShareKit/SinaWeibo
    - pod lib lint --subspec=ShareKit/Vkontakte
    - pod lib lint --subspec=ShareKit/Instagram
    #- pod lib lint --subspec=ShareKit/GooglePlus # Fails
    - xctool -project 'ShareKit.xcodeproj' -scheme 'Static Library' -configuration Release -sdk iphonesimulator -arch i386 build
    #- xctool -project 'ShareKit.xcodeproj' -scheme 'Static Library' -configuration Release -sdk iphonesimulator -arch i386 test # Fails
    - xctool -project 'ShareKit demo app.xcodeproj' -scheme 'ShareKit demo app' -configuration Release -sdk iphonesimulator -arch i386 build
