
language: objective-c

before_install:
    - gem install cocoapods --pre --quiet
    - pod --version
    - pod setup --silent
    - pod repo update --silent

script:
    - pod lib lint --verbose
    - xctool -project 'ShareKit.xcodeproj' -scheme 'Static Library' -configuration Release -sdk iphonesimulator -arch i386 build
    - xctool -project 'ShareKit.xcodeproj' -scheme 'Static Library' -configuration Release -sdk iphonesimulator -arch i386 test
    - xctool -project 'ShareKit demo app.xcodeproj' -scheme 'ShareKit demo app' -configuration Release -sdk iphonesimulator -arch i386 build
